# Eureka配置：配置服务注册中心地址
eureka:
  client:
    service-url:
      # 注册中心地址7001-7003
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7004.com:7004/eureka/,http://eureka7005.com:7005/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001 #修改Eureka上的默认描述信息
    #info配置
info:
  app.name: leon-springcloud #项目的名称
  company.name: com.leon #公司的名称

spring:
  application:
    name: springcloud-provider-dept
server:
  port: 8001
